<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "speciality_to_doctor".
 *
 * @property int $id
 * @property int|null $doctor_id
 * @property int|null $hospital_id
 * @property int|null $speciality_id
 * @property int|null $status
 */
class DoctorToSpeciality extends \soft\db\ActiveRecord
{
    //<editor-fold desc="Parent" defaultstate="collapsed">


    public function fields()
    {
        return [
            'speciality',
            'doctor',
            'doctorsCount',
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'speciality_to_doctor';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['doctor_id', 'hospital_id', 'speciality_id', 'status','average_accept_time','hospital_id'], 'integer'],
            [['work_begin', 'work_end', 'lunch_begin', 'lunch_end','accept_days'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function labels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'doctor_id' => Yii::t('app', 'Doctor ID'),
            'hospital_id' => Yii::t('app', 'Hospital ID'),
            'speciality_id' => Yii::t('app', 'Speciality ID'),
            'status' => Yii::t('app', 'Status'),
        ];
    }

    //</editor-fold>

    public function getSpeciality()
    {
        return $this->hasOne(Speciality::class, ['id' => 'speciality_id']);
    }

    public function getDoctor()
    {
        return $this->hasOne(Doctor::class, ['id' => 'doctor_id']);
    }

    public function getDoctorsCount()
    {
        return self::find()
            ->andWhere(['hospital_id' => user('hospital_id')])
            ->andWhere(['speciality_id' => $this->speciality_id])
            ->count('doctor_id');
    }

}
