<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "transactions".
 *
 * @property int $id
 * @property int|null $client_id
 * @property int|null $queue_id
 * @property int|null $amount
 * @property string|null $payment_method
 * @property int|null $datetime
 * @property int|null $cash
 * @property int|null $card
 * @property string|null $comment
 */
class Transactions extends \soft\db\ActiveRecord
{


    const TYPE_CASH = 1;
    const TYPE_TERMINAL = 2;
    const TYPE_BANK = 3;
    const TYPE_PAYME = 4;
    const TYPE_CLICK = 5;
    const TYPE_OTHER = 6;

    //<editor-fold desc="Parent" defaultstate="collapsed">

    public function fields()
    {
        return [
            'id',
            'cash',
            'f_cash' => function ($model) {
                return Yii::$app->formatter->asSum($model->cash);
            },
            'card',
            'f_card' => function ($model) {
                return Yii::$app->formatter->asSum($model->card);
            },
            'datetime' => function ($model) {
                return date("d.m.Y H:i:s", $model->datetime);
            },
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'transactions';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['client_id', 'queue_id', 'cash', 'card', 'amount', 'datetime'], 'integer'],
            [['comment'], 'string'],
            [['payment_method'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function labels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'client_id' => Yii::t('app', 'Client ID'),
            'queue_id' => Yii::t('app', 'Queue ID'),
            'amount' => Yii::t('app', 'Amount'),
            'payment_method' => Yii::t('app', 'Payment Method'),
            'datetime' => Yii::t('app', 'Datetime'),
            'comment' => Yii::t('app', 'Comment'),
            'cash' => Yii::t('app', 'Cash'),
            'card' => Yii::t('app', 'Card'),
        ];
    }

    //</editor-fold>

    public function getQueue()
    {
        return $this->hasOne(Queue::class, ['id' => "queue_id"]);
    }

    public function getClient()
    {
        return $this->hasOne(Client::class, ['id' => "queue_id"]);
    }

    public function getDoctor()
    {
        return $this->hasOne(Doctor::class, ['id' => "doctor_id"])->via('queue');
    }
}
