<?php

namespace backend\models;

use mohorev\file\UploadImageBehavior;
use Yii;

/**
 * This is the model class for table "hospital".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $logo
 * @property string|null $image
 * @property string|null $phone
 * @property string|null $username
 * @property string|null $password
 * @property string|null $fax
 * @property string|null $email
 * @property string|null $address
 * @property string|null $lat
 * @property string|null $long
 * @property int|null $status
 * @property int|null $deleted
 */
class Hospital extends \soft\db\ActiveRecord
{

    public function fields()
    {
        return [
            "id",
            "name",
            "phone",
            "fax",
            "email",
            "address",
            "lat",
            "long",
            "status",
            "deleted",
            "username",
            "password",
            "imageUrl",
            "logoUrl",
        ]; // TODO: Change the autogenerated stub
    }

    //<editor-fold desc="Parent" defaultstate="collapsed">

    public function behaviors()
    {
        return [
            [
                'class' => UploadImageBehavior::class,
                'attribute' => 'image',
                'deleteOriginalFile' => true,
                'scenarios' => ['default'],
                'path' => '@frontend/web/uploads/images/hospital/{id}',
                'url' => '/uploads/images/hospital/{id}',
                'thumbs' => [
                    'preview' => ['width' => 250],
                ],
            ],

            [
                'class' => UploadImageBehavior::class,
                'attribute' => 'logo',
                'deleteOriginalFile' => true,
                'scenarios' => ['default'],
                'path' => '@frontend/web/uploads/images/hospital/{id}',
                'url' => '/uploads/images/hospital/{id}',
                'thumbs' => [
                    'preview' => ['width' => 250],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'hospital';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['address', 'username', 'password'], 'string'],
            ['username', 'unique', 'message' => 'Ushbu login avvalroq band qilingan.'],
            [['logo', 'image'], 'image'],
            [['status', 'deleted'], 'integer'],
            [['name', 'phone', 'fax', 'email', 'lat', 'long'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function labels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'logo' => Yii::t('app', 'Logo'),
            'image' => Yii::t('app', 'Image'),
            'phone' => Yii::t('app', 'Phone'),
            'fax' => Yii::t('app', 'Fax'),
            'email' => Yii::t('app', 'Email'),
            'address' => Yii::t('app', 'Address'),
            'lat' => Yii::t('app', 'Lat'),
            'long' => Yii::t('app', 'Long'),
            'status' => Yii::t('app', 'Status'),
            'deleted' => Yii::t('app', 'Deleted'),
            'password' => Yii::t('app', 'New Password'),
            'username' => Yii::t('app', 'Username'),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function find()
    {
        return new \backend\models\query\HospitalQuery(get_called_class());
    }

    //</editor-fold>


    public function getImageUrl()
    {
        return $this->getThumbUploadUrl('image', 'preview');
    }

    public function getLogoUrl()
    {
        return $this->getThumbUploadUrl('logo', 'preview');
    }
}
