<?php

namespace backend\models;

use common\models\User;
use mohorev\file\UploadImageBehavior;
use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string|null $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string|null $password_reset_token
 * @property string|null $email
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property string|null $first_name
 * @property string|null $last_name
 * @property string|null $phone
 * @property string|null $image
 * @property int|null $type_id
 * @property string|null $father_name
 * @property string|null $birth_date
 * @property int|null $gender
 * @property int|null $province_id
 * @property int|null $region_id
 *
 * @property Car[] $cars
 * @property Car[] $cars0
 * @property Car[] $cars1
 * @property Client[] $clients
 * @property Client[] $clients0
 * @property Order[] $orders
 * @property Order[] $orders0
 * @property Order[] $orders1
 * @property Tariff[] $tariffs
 * @property Tariff[] $tariffs0
 */
class HospitalAdmin extends \soft\db\ActiveRecord
{

    public $password;
    //<editor-fold desc="Parent" defaultstate="collapsed">

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    public function beforeSave($insert)
    {

        $this->password_hash = Yii::$app->security->generatePasswordHash($this->password);
        $this->auth_key = Yii::$app->security->generateRandomString(16) . '_' . time();
        $this->type_id = User::TYPE_HOSPITAL_ADMIN;
        $this->email = $this->phone;
        $this->status = User::STATUS_ACTIVE;

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            [
                'class' => UploadImageBehavior::class,
                'attribute' => 'image',
                'deleteOriginalFile' => true,
                'scenarios' => ['default'],
                'path' => '@frontend/web/uploads/images/hospital-admin/{id}',
                'url' => '/uploads/images/hospital-admin/{id}',
                'thumbs' => [
                    'preview' => ['width' => 250],
                ],
            ],
            [
                'class' => TimestampBehavior::class
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['hospital_id', 'unique'],
            [['auth_key', 'password_hash', 'created_at', 'updated_at'], 'safe'],
            [['status', 'created_at', 'updated_at', 'type_id', 'gender', 'province_id', 'region_id'], 'integer'],
            [['birth_date'], 'safe'],
            [['username', 'first_name', 'last_name', 'phone'], 'string', 'max' => 100],
            [['auth_key'], 'string', 'max' => 32],
            [['password_hash', 'password', 'password_reset_token', 'email', 'father_name'], 'string', 'max' => 255],
            [['username'], 'unique'],
            ['image', 'image'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function labels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'username' => Yii::t('app', 'Username'),
            'auth_key' => Yii::t('app', 'Auth Key'),
            'password_hash' => Yii::t('app', 'Password Hash'),
            'password_reset_token' => Yii::t('app', 'Password Reset Token'),
            'email' => Yii::t('app', 'Email'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'first_name' => Yii::t('app', 'First Name'),
            'last_name' => Yii::t('app', 'Last Name'),
            'phone' => Yii::t('app', 'Phone'),
            'image' => Yii::t('app', 'Image'),
            'type_id' => Yii::t('app', 'Type ID'),
            'father_name' => Yii::t('app', 'Father Name'),
            'birth_date' => Yii::t('app', 'Birth Date'),
            'gender' => Yii::t('app', 'Gender'),
            'province_id' => Yii::t('app', 'Province ID'),
            'region_id' => Yii::t('app', 'Region ID'),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function find()
    {
        return parent::find()->andWhere(['user.type_id' => User::TYPE_HOSPITAL_ADMIN]);
    }

    public function getImageUrl()
    {
        return $this->getThumbUploadUrl('image', 'preview');
    }
    //</editor-fold>

    //<editor-fold desc="Relations" defaultstate="collapsed">

    /**
     * @return \yii\db\ActiveQuery|\backend\models\query\CarQuery
     */
    public function getHospital()
    {
        return $this->hasOne(Hospital::className(), ['id' => 'hospital_id']);
    }


    //</editor-fold>
}
