<?php

namespace common\resources;

use common\models\Queue;

class HomeQueue extends Queue
{
    public function fields()
    {
        return [
            'id',
            "patient_id",
            "queue_number",
            "doctor",
            "date",
        ]; // TODO: Change the autogenerated stub
    }

    public function getDoctor()
    {
        return $this->hasMany(HomeDoctor::class, ['id' => 'doctor_id']);
    }
}