<?php

namespace common\resources;

class HomeDoctor extends \common\models\Doctor
{

    public function fields()
    {
        return [
            'id',
            'first_name',
            'last_name',
            'father_name',
            'imageUrl',
            'rate',
            'speciality' => function ($model) {
                return $model->speciality->name;
            },
        ]; // TODO: Change the autogenerated stub
    }

}